name: Codecov
on: [push, pull_request]
jobs:
  Codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests and collect coverage
        run: pytest --cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
